### ISSUE TITLE
Reactivation of foreign key constraints failes

### ISSUE THREAD

**Issue by mdoerschmidt** [hudeany/dbimport#2]
Deactivation and reactivation seems to take place before and after importing table content. In some cases reactivation of such constraints fails because the referenced table has not been imported.

I think, there are two solutions:

1. Take care of the import order of tables or
2. Deactivate constraints before first table is imported and reactivate constraints after last table has been reactivated.

This may also be a good solutions for triggers, etc.

**Comment by hudeany** [comment]
I am checking this issue with the current version DbImport 24.1.25.
The following only happens if the deactivation of foreign key constraints was activated by checkbox in GUI, in the console menu or by CLI parameter.

Currently the deactivation of foreign key constraints of all database tables is executed before importing the first table and reactivated after the last table was imported.
(See DbImportWorker lines 378 ff and DbImportMultiWorker lines 83 ff, DbImportMultiWorker uses DbImportWorker for import of single table but deactivates the single deactivation and reactivation therein)
Also the import uses the defined tables for import in the given order.
Be aware that wildcard usage does not show any order of the tables. The reference structure of the tables is not analysed on wildcard usage. Wildcard tables will be executed in alphabetical order.

I think the problem in your case of "reactivation ... fails because the referenced table has not been imported" seems to be, that the specific constraint cannot be reactivated, because of the missing referenced values, which have not been imported. Constraints can only be reactivated if the constraint references are all valid after the reactivation.
By now the db drivers error message and its reported cause for this are only logged into the stderr stream. But the result of not being able to reactivate some constraints is also logged into the gui with the name of the still inactive constraints.

The same goes for trigger deactivation and reactivation, which is done right after the constraint deactivation and reactivation if configured to do so.

Still there might be a bug in there especially when using the MultiTable-Import, which remotely uses the SingleImport classes, but I can't see it by now.

Is this explanation helpful?

**Comment by hudeany** [comment]
Seems like your data for import was missing some values,
